<script setup lang="ts">import { leaders, products, services, stats } from '~/data/site'; useSeoMeta({ title: 'Enterprise Software & Digital Solutions', description: 'Paramount International builds dependable enterprise software, cloud platforms, integrations and business products in Bangladesh.' })</script>
<template><div>
  <section class="relative overflow-hidden bg-[#071d3d] py-24 text-white sm:py-32 lg:py-40"><div class="absolute right-[-12rem] top-[-12rem] h-[38rem] w-[38rem] rounded-full border border-[#c58b1b]/20"></div><div class="absolute right-[-5rem] top-[-5rem] h-[26rem] w-[26rem] rounded-full bg-[#123965]/70"></div><AppContainer><div class="relative grid items-center gap-14 lg:grid-cols-[1.15fr_.85fr]">
    <div><p class="eyebrow">Established 13 June 2022 · Dhaka, Bangladesh</p><h1 class="mt-6 text-5xl font-black leading-[.98] tracking-tight sm:text-7xl">Enterprise technology built for real operations.</h1><p class="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Paramount International designs and develops secure software products, integrated business platforms and cloud-ready solutions that help organizations work with greater clarity, control and confidence.</p><div class="mt-9 flex flex-wrap gap-4"><NuxtLink to="/contact" class="rounded-full bg-[#c58b1b] px-7 py-4 text-sm font-bold text-[#071d3d] hover:bg-[#e0b24d]">Discuss your requirement</NuxtLink><NuxtLink to="/portfolio" class="rounded-full border border-white/20 px-7 py-4 text-sm font-bold hover:border-[#e0b24d] hover:text-[#e0b24d]">View technology experience</NuxtLink></div></div>
    <div class="mx-auto w-full max-w-lg rounded-[2rem] border border-white/10 bg-white/[.055] p-5 backdrop-blur"><p class="px-2 pb-4 text-xs font-black uppercase tracking-[.22em] text-[#e0b24d]">Software capability</p><div class="grid grid-cols-2 gap-3"><div v-for="(s, i) in services.slice(0, 4)" :key="s.slug" class="rounded-2xl p-5" :class="i === 0 ? 'bg-[#c58b1b] text-[#071d3d]' : 'bg-[#102e51] text-white'"><p class="text-xs font-black opacity-65">{{ s.number }}</p><p class="mt-8 font-bold leading-tight">{{ s.title }}</p></div></div></div>
  </div></AppContainer></section>
  <section class="bg-[#f5f1e8] py-20"><AppContainer><div class="grid gap-8 sm:grid-cols-2 lg:grid-cols-4"><div v-for="([value, label]) in stats" :key="label" class="border-l-2 border-[#c58b1b] pl-5"><p class="text-4xl font-black text-[#071d3d]">{{ value }}</p><p class="mt-2 text-sm leading-6 text-slate-600">{{ label }}</p></div></div></AppContainer></section>
  <section class="py-24 sm:py-32"><AppContainer><div class="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p class="eyebrow">What we deliver</p><h2 class="section-title">From business requirement to supported solution.</h2><p class="section-copy">Our team supports the full software lifecycle: discovery, architecture, product engineering, deployment, integration and ongoing improvement.</p></div><div class="grid gap-5 md:grid-cols-2"><NuxtLink v-for="s in services" :key="s.slug" :to="`/services#${s.slug}`" class="group rounded-3xl border border-slate-200 bg-white p-7 transition hover:-translate-y-1 hover:border-[#c58b1b] hover:shadow-xl"><p class="text-xs font-black text-[#b57b10]">{{ s.number }}</p><h3 class="mt-8 text-xl font-black text-[#071d3d]">{{ s.title }}</h3><p class="mt-4 text-sm leading-7 text-slate-600">{{ s.summary }}</p><p class="mt-6 text-sm font-bold text-[#123965]">Explore capability →</p></NuxtLink></div></div></AppContainer></section>
  <section class="bg-[#071d3d] py-24 text-white sm:py-32"><AppContainer><div class="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="eyebrow">Paramount products</p><h2 class="mt-4 text-4xl font-black sm:text-5xl">Modular platforms for growing operations.</h2></div><NuxtLink to="/products" class="text-sm font-bold text-[#e0b24d]">Explore all products →</NuxtLink></div><div class="mt-14 grid gap-5 md:grid-cols-3"><article v-for="p in products.slice(0, 3)" :key="p.title" class="rounded-3xl bg-white/5 p-7"><h3 class="text-xl font-black">{{ p.title }}</h3><p class="mt-4 text-sm leading-7 text-slate-300">{{ p.summary }}</p></article></div></AppContainer></section>
  <section class="py-24 sm:py-32"><AppContainer><div class="flex items-end justify-between gap-6"><div><p class="eyebrow">Leadership</p><h2 class="section-title">Experience that connects strategy and delivery.</h2></div><NuxtLink to="/leadership" class="hidden text-sm font-bold text-[#123965] sm:block">Meet the team →</NuxtLink></div><div class="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><article v-for="l in leaders" :key="l.name" class="overflow-hidden rounded-3xl bg-[#f5f1e8]"><img :src="l.image" :alt="l.name" class="h-64 w-full object-cover object-top"><div class="p-5"><h3 class="font-bold text-[#071d3d]">{{ l.name }}</h3><p class="mt-1 text-xs font-bold uppercase tracking-wider text-[#b57b10]">{{ l.role }}</p></div></article></div></AppContainer></section>
  <AppCta />
</div></template>
